[package]
name = "ngx-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
libc.workspace = true
nix.workspace = true
tokio.workspace = true
pcre2.workspace = true
md-5.workspace = true
sha1.workspace = true
crc32fast.workspace = true
memchr.workspace = true
openssl.workspace = true
openssl-sys.workspace = true
foreign-types.workspace = true
bytes.workspace = true
ngx-sys.workspace = true
rustix.workspace = true
socket2.workspace = true
mmap-rs.workspace = true
zerocopy.workspace = true
signal-hook = { workspace = true, features = ["extended-siginfo"] }
pwhash.workspace = true
blowfish.workspace = true
vm-memory.workspace = true
