//! The country tables of libGeoIP 1.6.12 (GeoIP.c): GeoIP_country_code,
//! GeoIP_country_code3, GeoIP_country_name (ISO-8859-1),
//! GeoIP_utf8_country_name and GeoIP_country_continent, indexed by the
//! country id of the databases.  Generated from GeoIP.c.

/// GeoIP_country_code
pub(super) static COUNTRY_CODE: [&[u8]; 256] = [
    b"--", b"AP", b"EU", b"AD", b"AE", b"AF", b"AG", b"AI",
    b"AL", b"AM", b"CW", b"AO", b"AQ", b"AR", b"AS", b"AT",
    b"AU", b"AW", b"AZ", b"BA", b"BB", b"BD", b"BE", b"BF",
    b"BG", b"BH", b"BI", b"BJ", b"BM", b"BN", b"BO", b"BR",
    b"BS", b"BT", b"BV", b"BW", b"BY", b"BZ", b"CA", b"CC",
    b"CD", b"CF", b"CG", b"CH", b"CI", b"CK", b"CL", b"CM",
    b"CN", b"CO", b"CR", b"CU", b"CV", b"CX", b"CY", b"CZ",
    b"DE", b"DJ", b"DK", b"DM", b"DO", b"DZ", b"EC", b"EE",
    b"EG", b"EH", b"ER", b"ES", b"ET", b"FI", b"FJ", b"FK",
    b"FM", b"FO", b"FR", b"SX", b"GA", b"GB", b"GD", b"GE",
    b"GF", b"GH", b"GI", b"GL", b"GM", b"GN", b"GP", b"GQ",
    b"GR", b"GS", b"GT", b"GU", b"GW", b"GY", b"HK", b"HM",
    b"HN", b"HR", b"HT", b"HU", b"ID", b"IE", b"IL", b"IN",
    b"IO", b"IQ", b"IR", b"IS", b"IT", b"JM", b"JO", b"JP",
    b"KE", b"KG", b"KH", b"KI", b"KM", b"KN", b"KP", b"KR",
    b"KW", b"KY", b"KZ", b"LA", b"LB", b"LC", b"LI", b"LK",
    b"LR", b"LS", b"LT", b"LU", b"LV", b"LY", b"MA", b"MC",
    b"MD", b"MG", b"MH", b"MK", b"ML", b"MM", b"MN", b"MO",
    b"MP", b"MQ", b"MR", b"MS", b"MT", b"MU", b"MV", b"MW",
    b"MX", b"MY", b"MZ", b"NA", b"NC", b"NE", b"NF", b"NG",
    b"NI", b"NL", b"NO", b"NP", b"NR", b"NU", b"NZ", b"OM",
    b"PA", b"PE", b"PF", b"PG", b"PH", b"PK", b"PL", b"PM",
    b"PN", b"PR", b"PS", b"PT", b"PW", b"PY", b"QA", b"RE",
    b"RO", b"RU", b"RW", b"SA", b"SB", b"SC", b"SD", b"SE",
    b"SG", b"SH", b"SI", b"SJ", b"SK", b"SL", b"SM", b"SN",
    b"SO", b"SR", b"ST", b"SV", b"SY", b"SZ", b"TC", b"TD",
    b"TF", b"TG", b"TH", b"TJ", b"TK", b"TM", b"TN", b"TO",
    b"TL", b"TR", b"TT", b"TV", b"TW", b"TZ", b"UA", b"UG",
    b"UM", b"US", b"UY", b"UZ", b"VA", b"VC", b"VE", b"VG",
    b"VI", b"VN", b"VU", b"WF", b"WS", b"YE", b"YT", b"RS",
    b"ZA", b"ZM", b"ME", b"ZW", b"A1", b"A2", b"O1", b"AX",
    b"GG", b"IM", b"JE", b"BL", b"MF", b"BQ", b"SS", b"O1",
];

/// GeoIP_country_code3
pub(super) static COUNTRY_CODE3: [&[u8]; 256] = [
    b"--", b"AP", b"EU", b"AND", b"ARE", b"AFG", b"ATG", b"AIA",
    b"ALB", b"ARM", b"CUW", b"AGO", b"ATA", b"ARG", b"ASM", b"AUT",
    b"AUS", b"ABW", b"AZE", b"BIH", b"BRB", b"BGD", b"BEL", b"BFA",
    b"BGR", b"BHR", b"BDI", b"BEN", b"BMU", b"BRN", b"BOL", b"BRA",
    b"BHS", b"BTN", b"BVT", b"BWA", b"BLR", b"BLZ", b"CAN", b"CCK",
    b"COD", b"CAF", b"COG", b"CHE", b"CIV", b"COK", b"CHL", b"CMR",
    b"CHN", b"COL", b"CRI", b"CUB", b"CPV", b"CXR", b"CYP", b"CZE",
    b"DEU", b"DJI", b"DNK", b"DMA", b"DOM", b"DZA", b"ECU", b"EST",
    b"EGY", b"ESH", b"ERI", b"ESP", b"ETH", b"FIN", b"FJI", b"FLK",
    b"FSM", b"FRO", b"FRA", b"SXM", b"GAB", b"GBR", b"GRD", b"GEO",
    b"GUF", b"GHA", b"GIB", b"GRL", b"GMB", b"GIN", b"GLP", b"GNQ",
    b"GRC", b"SGS", b"GTM", b"GUM", b"GNB", b"GUY", b"HKG", b"HMD",
    b"HND", b"HRV", b"HTI", b"HUN", b"IDN", b"IRL", b"ISR", b"IND",
    b"IOT", b"IRQ", b"IRN", b"ISL", b"ITA", b"JAM", b"JOR", b"JPN",
    b"KEN", b"KGZ", b"KHM", b"KIR", b"COM", b"KNA", b"PRK", b"KOR",
    b"KWT", b"CYM", b"KAZ", b"LAO", b"LBN", b"LCA", b"LIE", b"LKA",
    b"LBR", b"LSO", b"LTU", b"LUX", b"LVA", b"LBY", b"MAR", b"MCO",
    b"MDA", b"MDG", b"MHL", b"MKD", b"MLI", b"MMR", b"MNG", b"MAC",
    b"MNP", b"MTQ", b"MRT", b"MSR", b"MLT", b"MUS", b"MDV", b"MWI",
    b"MEX", b"MYS", b"MOZ", b"NAM", b"NCL", b"NER", b"NFK", b"NGA",
    b"NIC", b"NLD", b"NOR", b"NPL", b"NRU", b"NIU", b"NZL", b"OMN",
    b"PAN", b"PER", b"PYF", b"PNG", b"PHL", b"PAK", b"POL", b"SPM",
    b"PCN", b"PRI", b"PSE", b"PRT", b"PLW", b"PRY", b"QAT", b"REU",
    b"ROU", b"RUS", b"RWA", b"SAU", b"SLB", b"SYC", b"SDN", b"SWE",
    b"SGP", b"SHN", b"SVN", b"SJM", b"SVK", b"SLE", b"SMR", b"SEN",
    b"SOM", b"SUR", b"STP", b"SLV", b"SYR", b"SWZ", b"TCA", b"TCD",
    b"ATF", b"TGO", b"THA", b"TJK", b"TKL", b"TKM", b"TUN", b"TON",
    b"TLS", b"TUR", b"TTO", b"TUV", b"TWN", b"TZA", b"UKR", b"UGA",
    b"UMI", b"USA", b"URY", b"UZB", b"VAT", b"VCT", b"VEN", b"VGB",
    b"VIR", b"VNM", b"VUT", b"WLF", b"WSM", b"YEM", b"MYT", b"SRB",
    b"ZAF", b"ZMB", b"MNE", b"ZWE", b"A1", b"A2", b"O1", b"ALA",
    b"GGY", b"IMN", b"JEY", b"BLM", b"MAF", b"BES", b"SSD", b"O1",
];

/// GeoIP_country_name
pub(super) static COUNTRY_NAME: [&[u8]; 256] = [
    b"N/A",
    b"Asia/Pacific Region",
    b"Europe",
    b"Andorra",
    b"United Arab Emirates",
    b"Afghanistan",
    b"Antigua and Barbuda",
    b"Anguilla",
    b"Albania",
    b"Armenia",
    b"Curacao",
    b"Angola",
    b"Antarctica",
    b"Argentina",
    b"American Samoa",
    b"Austria",
    b"Australia",
    b"Aruba",
    b"Azerbaijan",
    b"Bosnia and Herzegovina",
    b"Barbados",
    b"Bangladesh",
    b"Belgium",
    b"Burkina Faso",
    b"Bulgaria",
    b"Bahrain",
    b"Burundi",
    b"Benin",
    b"Bermuda",
    b"Brunei Darussalam",
    b"Bolivia",
    b"Brazil",
    b"Bahamas",
    b"Bhutan",
    b"Bouvet Island",
    b"Botswana",
    b"Belarus",
    b"Belize",
    b"Canada",
    b"Cocos (Keeling) Islands",
    b"Congo, The Democratic Republic of the",
    b"Central African Republic",
    b"Congo",
    b"Switzerland",
    b"Cote D'Ivoire",
    b"Cook Islands",
    b"Chile",
    b"Cameroon",
    b"China",
    b"Colombia",
    b"Costa Rica",
    b"Cuba",
    b"Cape Verde",
    b"Christmas Island",
    b"Cyprus",
    b"Czech Republic",
    b"Germany",
    b"Djibouti",
    b"Denmark",
    b"Dominica",
    b"Dominican Republic",
    b"Algeria",
    b"Ecuador",
    b"Estonia",
    b"Egypt",
    b"Western Sahara",
    b"Eritrea",
    b"Spain",
    b"Ethiopia",
    b"Finland",
    b"Fiji",
    b"Falkland Islands (Malvinas)",
    b"Micronesia, Federated States of",
    b"Faroe Islands",
    b"France",
    b"Sint Maarten (Dutch part)",
    b"Gabon",
    b"United Kingdom",
    b"Grenada",
    b"Georgia",
    b"French Guiana",
    b"Ghana",
    b"Gibraltar",
    b"Greenland",
    b"Gambia",
    b"Guinea",
    b"Guadeloupe",
    b"Equatorial Guinea",
    b"Greece",
    b"South Georgia and the South Sandwich Islands",
    b"Guatemala",
    b"Guam",
    b"Guinea-Bissau",
    b"Guyana",
    b"Hong Kong",
    b"Heard Island and McDonald Islands",
    b"Honduras",
    b"Croatia",
    b"Haiti",
    b"Hungary",
    b"Indonesia",
    b"Ireland",
    b"Israel",
    b"India",
    b"British Indian Ocean Territory",
    b"Iraq",
    b"Iran, Islamic Republic of",
    b"Iceland",
    b"Italy",
    b"Jamaica",
    b"Jordan",
    b"Japan",
    b"Kenya",
    b"Kyrgyzstan",
    b"Cambodia",
    b"Kiribati",
    b"Comoros",
    b"Saint Kitts and Nevis",
    b"Korea, Democratic People's Republic of",
    b"Korea, Republic of",
    b"Kuwait",
    b"Cayman Islands",
    b"Kazakhstan",
    b"Lao People's Democratic Republic",
    b"Lebanon",
    b"Saint Lucia",
    b"Liechtenstein",
    b"Sri Lanka",
    b"Liberia",
    b"Lesotho",
    b"Lithuania",
    b"Luxembourg",
    b"Latvia",
    b"Libya",
    b"Morocco",
    b"Monaco",
    b"Moldova, Republic of",
    b"Madagascar",
    b"Marshall Islands",
    b"Macedonia",
    b"Mali",
    b"Myanmar",
    b"Mongolia",
    b"Macau",
    b"Northern Mariana Islands",
    b"Martinique",
    b"Mauritania",
    b"Montserrat",
    b"Malta",
    b"Mauritius",
    b"Maldives",
    b"Malawi",
    b"Mexico",
    b"Malaysia",
    b"Mozambique",
    b"Namibia",
    b"New Caledonia",
    b"Niger",
    b"Norfolk Island",
    b"Nigeria",
    b"Nicaragua",
    b"Netherlands",
    b"Norway",
    b"Nepal",
    b"Nauru",
    b"Niue",
    b"New Zealand",
    b"Oman",
    b"Panama",
    b"Peru",
    b"French Polynesia",
    b"Papua New Guinea",
    b"Philippines",
    b"Pakistan",
    b"Poland",
    b"Saint Pierre and Miquelon",
    b"Pitcairn Islands",
    b"Puerto Rico",
    b"Palestinian Territory",
    b"Portugal",
    b"Palau",
    b"Paraguay",
    b"Qatar",
    b"Reunion",
    b"Romania",
    b"Russian Federation",
    b"Rwanda",
    b"Saudi Arabia",
    b"Solomon Islands",
    b"Seychelles",
    b"Sudan",
    b"Sweden",
    b"Singapore",
    b"Saint Helena",
    b"Slovenia",
    b"Svalbard and Jan Mayen",
    b"Slovakia",
    b"Sierra Leone",
    b"San Marino",
    b"Senegal",
    b"Somalia",
    b"Suriname",
    b"Sao Tome and Principe",
    b"El Salvador",
    b"Syrian Arab Republic",
    b"Swaziland",
    b"Turks and Caicos Islands",
    b"Chad",
    b"French Southern Territories",
    b"Togo",
    b"Thailand",
    b"Tajikistan",
    b"Tokelau",
    b"Turkmenistan",
    b"Tunisia",
    b"Tonga",
    b"Timor-Leste",
    b"Turkey",
    b"Trinidad and Tobago",
    b"Tuvalu",
    b"Taiwan",
    b"Tanzania, United Republic of",
    b"Ukraine",
    b"Uganda",
    b"United States Minor Outlying Islands",
    b"United States",
    b"Uruguay",
    b"Uzbekistan",
    b"Holy See (Vatican City State)",
    b"Saint Vincent and the Grenadines",
    b"Venezuela",
    b"Virgin Islands, British",
    b"Virgin Islands, U.S.",
    b"Vietnam",
    b"Vanuatu",
    b"Wallis and Futuna",
    b"Samoa",
    b"Yemen",
    b"Mayotte",
    b"Serbia",
    b"South Africa",
    b"Zambia",
    b"Montenegro",
    b"Zimbabwe",
    b"Anonymous Proxy",
    b"Satellite Provider",
    b"Other",
    b"Aland Islands",
    b"Guernsey",
    b"Isle of Man",
    b"Jersey",
    b"Saint Barthelemy",
    b"Saint Martin",
    b"Bonaire, Saint Eustatius and Saba",
    b"South Sudan",
    b"Other",
];

/// GeoIP_utf8_country_name
pub(super) static UTF8_COUNTRY_NAME: [&[u8]; 256] = [
    b"N/A",
    b"Asia/Pacific Region",
    b"Europe",
    b"Andorra",
    b"United Arab Emirates",
    b"Afghanistan",
    b"Antigua and Barbuda",
    b"Anguilla",
    b"Albania",
    b"Armenia",
    b"Cura\xc3\xa7ao",
    b"Angola",
    b"Antarctica",
    b"Argentina",
    b"American Samoa",
    b"Austria",
    b"Australia",
    b"Aruba",
    b"Azerbaijan",
    b"Bosnia and Herzegovina",
    b"Barbados",
    b"Bangladesh",
    b"Belgium",
    b"Burkina Faso",
    b"Bulgaria",
    b"Bahrain",
    b"Burundi",
    b"Benin",
    b"Bermuda",
    b"Brunei Darussalam",
    b"Bolivia",
    b"Brazil",
    b"Bahamas",
    b"Bhutan",
    b"Bouvet Island",
    b"Botswana",
    b"Belarus",
    b"Belize",
    b"Canada",
    b"Cocos (Keeling) Islands",
    b"Congo, The Democratic Republic of the",
    b"Central African Republic",
    b"Congo",
    b"Switzerland",
    b"Cote D'Ivoire",
    b"Cook Islands",
    b"Chile",
    b"Cameroon",
    b"China",
    b"Colombia",
    b"Costa Rica",
    b"Cuba",
    b"Cape Verde",
    b"Christmas Island",
    b"Cyprus",
    b"Czech Republic",
    b"Germany",
    b"Djibouti",
    b"Denmark",
    b"Dominica",
    b"Dominican Republic",
    b"Algeria",
    b"Ecuador",
    b"Estonia",
    b"Egypt",
    b"Western Sahara",
    b"Eritrea",
    b"Spain",
    b"Ethiopia",
    b"Finland",
    b"Fiji",
    b"Falkland Islands (Malvinas)",
    b"Micronesia, Federated States of",
    b"Faroe Islands",
    b"France",
    b"Sint Maarten (Dutch part)",
    b"Gabon",
    b"United Kingdom",
    b"Grenada",
    b"Georgia",
    b"French Guiana",
    b"Ghana",
    b"Gibraltar",
    b"Greenland",
    b"Gambia",
    b"Guinea",
    b"Guadeloupe",
    b"Equatorial Guinea",
    b"Greece",
    b"South Georgia and the South Sandwich Islands",
    b"Guatemala",
    b"Guam",
    b"Guinea-Bissau",
    b"Guyana",
    b"Hong Kong",
    b"Heard Island and McDonald Islands",
    b"Honduras",
    b"Croatia",
    b"Haiti",
    b"Hungary",
    b"Indonesia",
    b"Ireland",
    b"Israel",
    b"India",
    b"British Indian Ocean Territory",
    b"Iraq",
    b"Iran, Islamic Republic of",
    b"Iceland",
    b"Italy",
    b"Jamaica",
    b"Jordan",
    b"Japan",
    b"Kenya",
    b"Kyrgyzstan",
    b"Cambodia",
    b"Kiribati",
    b"Comoros",
    b"Saint Kitts and Nevis",
    b"Korea, Democratic People's Republic of",
    b"Korea, Republic of",
    b"Kuwait",
    b"Cayman Islands",
    b"Kazakhstan",
    b"Lao People's Democratic Republic",
    b"Lebanon",
    b"Saint Lucia",
    b"Liechtenstein",
    b"Sri Lanka",
    b"Liberia",
    b"Lesotho",
    b"Lithuania",
    b"Luxembourg",
    b"Latvia",
    b"Libya",
    b"Morocco",
    b"Monaco",
    b"Moldova, Republic of",
    b"Madagascar",
    b"Marshall Islands",
    b"Macedonia",
    b"Mali",
    b"Myanmar",
    b"Mongolia",
    b"Macau",
    b"Northern Mariana Islands",
    b"Martinique",
    b"Mauritania",
    b"Montserrat",
    b"Malta",
    b"Mauritius",
    b"Maldives",
    b"Malawi",
    b"Mexico",
    b"Malaysia",
    b"Mozambique",
    b"Namibia",
    b"New Caledonia",
    b"Niger",
    b"Norfolk Island",
    b"Nigeria",
    b"Nicaragua",
    b"Netherlands",
    b"Norway",
    b"Nepal",
    b"Nauru",
    b"Niue",
    b"New Zealand",
    b"Oman",
    b"Panama",
    b"Peru",
    b"French Polynesia",
    b"Papua New Guinea",
    b"Philippines",
    b"Pakistan",
    b"Poland",
    b"Saint Pierre and Miquelon",
    b"Pitcairn Islands",
    b"Puerto Rico",
    b"Palestinian Territory",
    b"Portugal",
    b"Palau",
    b"Paraguay",
    b"Qatar",
    b"Reunion",
    b"Romania",
    b"Russian Federation",
    b"Rwanda",
    b"Saudi Arabia",
    b"Solomon Islands",
    b"Seychelles",
    b"Sudan",
    b"Sweden",
    b"Singapore",
    b"Saint Helena",
    b"Slovenia",
    b"Svalbard and Jan Mayen",
    b"Slovakia",
    b"Sierra Leone",
    b"San Marino",
    b"Senegal",
    b"Somalia",
    b"Suriname",
    b"Sao Tome and Principe",
    b"El Salvador",
    b"Syrian Arab Republic",
    b"Swaziland",
    b"Turks and Caicos Islands",
    b"Chad",
    b"French Southern Territories",
    b"Togo",
    b"Thailand",
    b"Tajikistan",
    b"Tokelau",
    b"Turkmenistan",
    b"Tunisia",
    b"Tonga",
    b"Timor-Leste",
    b"Turkey",
    b"Trinidad and Tobago",
    b"Tuvalu",
    b"Taiwan",
    b"Tanzania, United Republic of",
    b"Ukraine",
    b"Uganda",
    b"United States Minor Outlying Islands",
    b"United States",
    b"Uruguay",
    b"Uzbekistan",
    b"Holy See (Vatican City State)",
    b"Saint Vincent and the Grenadines",
    b"Venezuela",
    b"Virgin Islands, British",
    b"Virgin Islands, U.S.",
    b"Vietnam",
    b"Vanuatu",
    b"Wallis and Futuna",
    b"Samoa",
    b"Yemen",
    b"Mayotte",
    b"Serbia",
    b"South Africa",
    b"Zambia",
    b"Montenegro",
    b"Zimbabwe",
    b"Anonymous Proxy",
    b"Satellite Provider",
    b"Other",
    b"Aland Islands",
    b"Guernsey",
    b"Isle of Man",
    b"Jersey",
    b"Saint Barthelemy",
    b"Saint Martin",
    b"Bonaire, Saint Eustatius and Saba",
    b"South Sudan",
    b"Other",
];

/// GeoIP_country_continent
pub(super) static COUNTRY_CONTINENT: [&[u8]; 256] = [
    b"--", b"AS", b"EU", b"EU", b"AS", b"AS", b"NA", b"NA",
    b"EU", b"AS", b"NA", b"AF", b"AN", b"SA", b"OC", b"EU",
    b"OC", b"NA", b"AS", b"EU", b"NA", b"AS", b"EU", b"AF",
    b"EU", b"AS", b"AF", b"AF", b"NA", b"AS", b"SA", b"SA",
    b"NA", b"AS", b"AN", b"AF", b"EU", b"NA", b"NA", b"AS",
    b"AF", b"AF", b"AF", b"EU", b"AF", b"OC", b"SA", b"AF",
    b"AS", b"SA", b"NA", b"NA", b"AF", b"AS", b"AS", b"EU",
    b"EU", b"AF", b"EU", b"NA", b"NA", b"AF", b"SA", b"EU",
    b"AF", b"AF", b"AF", b"EU", b"AF", b"EU", b"OC", b"SA",
    b"OC", b"EU", b"EU", b"NA", b"AF", b"EU", b"NA", b"AS",
    b"SA", b"AF", b"EU", b"NA", b"AF", b"AF", b"NA", b"AF",
    b"EU", b"AN", b"NA", b"OC", b"AF", b"SA", b"AS", b"AN",
    b"NA", b"EU", b"NA", b"EU", b"AS", b"EU", b"AS", b"AS",
    b"AS", b"AS", b"AS", b"EU", b"EU", b"NA", b"AS", b"AS",
    b"AF", b"AS", b"AS", b"OC", b"AF", b"NA", b"AS", b"AS",
    b"AS", b"NA", b"AS", b"AS", b"AS", b"NA", b"EU", b"AS",
    b"AF", b"AF", b"EU", b"EU", b"EU", b"AF", b"AF", b"EU",
    b"EU", b"AF", b"OC", b"EU", b"AF", b"AS", b"AS", b"AS",
    b"OC", b"NA", b"AF", b"NA", b"EU", b"AF", b"AS", b"AF",
    b"NA", b"AS", b"AF", b"AF", b"OC", b"AF", b"OC", b"AF",
    b"NA", b"EU", b"EU", b"AS", b"OC", b"OC", b"OC", b"AS",
    b"NA", b"SA", b"OC", b"OC", b"AS", b"AS", b"EU", b"NA",
    b"OC", b"NA", b"AS", b"EU", b"OC", b"SA", b"AS", b"AF",
    b"EU", b"EU", b"AF", b"AS", b"OC", b"AF", b"AF", b"EU",
    b"AS", b"AF", b"EU", b"EU", b"EU", b"AF", b"EU", b"AF",
    b"AF", b"SA", b"AF", b"NA", b"AS", b"AF", b"NA", b"AF",
    b"AN", b"AF", b"AS", b"AS", b"OC", b"AS", b"AF", b"OC",
    b"AS", b"EU", b"NA", b"OC", b"AS", b"AF", b"EU", b"AF",
    b"OC", b"NA", b"SA", b"AS", b"EU", b"NA", b"SA", b"NA",
    b"NA", b"AS", b"OC", b"OC", b"OC", b"AS", b"AF", b"EU",
    b"AF", b"AF", b"EU", b"AF", b"--", b"--", b"--", b"EU",
    b"EU", b"EU", b"EU", b"NA", b"NA", b"NA", b"AF", b"--",
];

